version: '2'

networks:
    default:
        external:
            name: nginx-proxy
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_MASK}.0/24

services:
    php:
        build: ./${PHP_VERSION}
        container_name: ${PROJECT}php
        volumes_from:
            - source
        ports:
            - '127.0.0.1:${PHP_PORT}:9000'
        links:
            - db
            - memcached
        networks:
            - bitrix
        extra_hosts:
            - "${PROJECT}:${SUBNET_MASK}.88"
        restart: always
    web_server:
        build: ./${WEB_SERVER_TYPE}
        container_name: ${PROJECT}webserver
        depends_on:
            - source
        volumes_from:
            - source
        links:
            - php
        environment:
            - VIRTUAL_HOST=${PROJECT}
            - LETSENCRYPT_HOST=${PROJECT}
            - LETSENCRYPT_EMAIL="ms@webbs.kz"
        networks:
            bitrix:
                ipv4_address: "${SUBNET_MASK}.88"
        restart: always
    db:
        build: ./${DB_SERVER_TYPE}
        container_name: ${PROJECT}db
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:${MYSQL_PORT}:3306'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --sql-mode=""
        networks:
            - bitrix
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: ${PROJECT}memcached
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:${MEMCACHED_PORT}:11211'
        networks:
            - bitrix
        restart: always
    adminer:
        image: dockette/adminer:full
        container_name: ${PROJECT}adminer
        links:
            - db:db
        ports:
            - '${INTERFACE}:${ADMINER_PORT}:80'
        environment:
            UPLOAD: 1024M # upload_max_filesize, post_max_size
        networks:
            - bitrix
    source:
        image: alpine:latest
        container_name: ${PROJECT}source
        volumes:
            - ./logs/${WEB_SERVER_TYPE}:/var/log/${WEB_SERVER_TYPE}
            - ./logs/php:/var/log/php
            - ./logs/db:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - db:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            - ./www/html:/var/www/html
            - ${SITE_PATH}:/var/www/${PROJECT}/bitrix
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - bitrix
